name: Build cordova-snap

on:
  push:
    branches:
      - master
    paths:
      - 'cordova-snap/VERSION'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Extract Tag from Dockerfile
        id: version
        run: |
          BASE_IMAGE=$(grep '^FROM' cordova-snap/Dockerfile | awk '{print $2}')
          TAG=$(echo "$BASE_IMAGE" | cut -d':' -f2)
          echo "Base image: $BASE_IMAGE"
          echo "Extracted tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BUILD_PATH: "cordova-snap/"
          DOCKERFILE: "cordova-snap/Dockerfile"
          IMAGE_NAME: "vparanoiaque/cordova-snap"
          TAG_NAME: ${{ steps.version.outputs.tag }}
          LATEST: "true"
          BUILDX: "true"
