name: Build logstash-oss-opensearch

on:
  push:
    branches:
      - master
    paths:
      - 'logstash-oss-opensearch/**'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Extract Tag from Dockerfile
        id: version
        run: |
          BASE_IMAGE=$(grep '^FROM' logstash-oss-opensearch/Dockerfile | awk '{print $2}')
          TAG=$(echo "$BASE_IMAGE" | cut -d':' -f2)
          echo "Base image: $BASE_IMAGE"
          echo "Extracted tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BUILD_PATH: "logstash-oss-opensearch/"
          DOCKERFILE:  "logstash-oss-opensearch/Dockerfile"
          IMAGE_NAME: "vparanoiaque/logstash-oss-opensearch"
          TAG_NAME: ${{ steps.version.outputs.tag }}
          LATEST: "true"
