name: Build nodejs-graphicsmagick

on:
  push:
    branches:
      - master
    paths:
      - 'nodejs-graphicsmagick/VERSION'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: pCYSl5EDgo/cat@master
        id: version
        with:
          path: nodejs-graphicsmagick/VERSION
      - name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          BUILD_PATH: "nodejs-graphicsmagick/"
          DOCKERFILE: "nodejs-graphicsmagick/Dockerfile"
          IMAGE_NAME: "vparanoiaque/nodejs-graphicsmagick"
          TAG_NAME: ${{ steps.version.outputs.text }}
          LATEST: "true"
          BUILDX: "true"
