name: Build nodejs-graphicsmagick

on:
  push:
    paths:
      - 'nodejs-graphicsmagick/VERSION'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: pCYSl5EDgo/cat@master
        id: version
        with:
          path: nodejs-graphicsmagick/VERSION
      - name: Build the Docker image
        run: docker build . --file nodejs-graphicsmagick/Dockerfile --tag vparanoiaque/nodejs-graphicsmagick:${{ steps.version.outputs.text }}
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push vparanoiaque/nodejs-graphicsmagick:${{ steps.version.outputs.text }}
