name: Build nodejs-graphicsmagick

on:
  push:
    paths:
      - 'nodejs-graphicsmagick/VERSION'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: pCYSl5EDgo/cat@master
        id: version
        with:
          path: nodejs-graphicsmagick/VERSION
      - name: Build the Docker image
        run: docker build . --file nodejs-graphicsmagick/Dockerfile --tag vparanoiaque/nodejs-graphicsmagick:${{ steps.version.outputs.text }}
